[package]
name = "nominalscript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_enums = "0.8.0"
clap = { version = "4.1.8", features = ["derive"] }
derive_more = "0.99.17"
env_logger = "0.10.0"
join-lazy-fmt = "0.9.2"
lazy_static = "1.4.0"
log = "0.4.17"
miette = { version = "5.5.0", features = ["fancy"] }
serde_json = "1.0.93"
thiserror = "1.0.38"
tree-sitter = "0.20.9"
tsconfig = "0.1.0"
